server:
  port: 8888

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: stephentorku
    password: gangsta
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 6E572C3A344B46294A404E635266556A5970327336763979244226452948404D